language: csharp
solution: DbKeeperNet.sln
sudo: required

addons:
  postgresql: "9.3"

before_script:
  - sudo apt-get install -qq firebird2.5-superclassic firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - cat /etc/default/firebird2.5 | grep ENABLE_FIREBIRD_SERVER
  - sudo service firebird2.5-superclassic start
  - psql -c 'create database pgtestdb;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'Password12!';" -U postgres
  - mysql -e 'create database mytest;' -uroot
  - mysql -e "SET PASSWORD = PASSWORD('Password12!');" -uroot
  - isql-fb -u SYSDBA -p masterkey -q -i .travis/travis-firebird.sql
  - .travis/oracle/install.sh

script: 
  - xbuild DbKeeperNet.sln /p:Configuration=Release
  - mono ./packages/NUnit.Runners.2.6.3/tools/nunit-console.exe -labels -include=pgsql,mysql,sqlite,firebird,oracle ./DbKeeperNet.Engine.Tests/bin/Release/DbKeeperNet.Engine.Tests.dll ./DbKeeperNet.Extensions.AspNetRolesAndMembership.Tests/bin/Release/DbKeeperNet.Extensions.AspNetRolesAndMembership.Tests.dll ./DbKeeperNet.Engine.Windows.Tests/bin/Release/DbKeeperNet.Engine.Windows.Tests.dll
  - mono ./packages/NUnit.Runners.2.6.3/tools/nunit-console.exe -labels ./DbKeeperNet.Engine.Tests/bin/Release/DbKeeperNet.Engine.Tests.dll ./DbKeeperNet.Extensions.AspNetRolesAndMembership.Tests/bin/Release/DbKeeperNet.Extensions.AspNetRolesAndMembership.Tests.dll ./DbKeeperNet.Engine.Windows.Tests/bin/Release/DbKeeperNet.Engine.Windows.Tests.dll
