version: 1.7.{build}
skip_tags: true
os: Windows Server 2012

services:
  - mssql2012sp1
  - mysql               # start MySQL 5.6 service
  - postgresql

install:
  - ECHO Install:
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" IF %APPVEYOR_REPO_BRANCH% == "master" SET CreateBinaries=true

configuration: Release

build_script:
  - ECHO Create databases
  - set pgpassword=Password12!
  - '"C:\Program Files\PostgreSQL\9.3\bin\psql.exe" -h localhost -U postgres -c "CREATE DATABASE pgtestdb"'
  - '"C:\Program Files\MySQL\MySQL Server 5.6\bin\mysql.exe" --user=root --password=Password12! -e "create database mytest"'
  - 'echo Create binaries: %CreateBinaries%'
  - 'msbuild.exe DbKeeperNet.msbuild /p:BuildNumber=%appveyor_build_version%.1 /t:CI'

artifacts:
  - path: .\*.zip
    name: ZipPackages
  - path: .\*.nupkg
    name: NugetPackages

test: off

