//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKeeperNet.Engine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PreconditionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreconditionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbKeeperNet.Engine.Resources.PreconditionMessages", typeof(PreconditionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type for condition {0} must be specified.
        /// </summary>
        internal static string DatabaseTypeEmpty {
            get {
                return ResourceManager.GetString("DatabaseTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign key name for condition {0} must be specified.
        /// </summary>
        internal static string ForeignKeyNameEmpty {
            get {
                return ResourceManager.GetString("ForeignKeyNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index name and table for condition {0} must be specified.
        /// </summary>
        internal static string IndexNameOrTableEmpty {
            get {
                return ResourceManager.GetString("IndexNameOrTableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition {0} is supported only for Oracle.
        /// </summary>
        internal static string OnlyOracleSupport {
            get {
                return ResourceManager.GetString("OnlyOracleSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key name and table for condition {0} must be specified.
        /// </summary>
        internal static string PrimaryKeyNameOrTableEmpty {
            get {
                return ResourceManager.GetString("PrimaryKeyNameOrTableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name must be specified as a parameter for condition {0}.
        /// </summary>
        internal static string RoleNameNotSpecified {
            get {
                return ResourceManager.GetString("RoleNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence name for condition {0} must be specified.
        /// </summary>
        internal static string SequenceNameEmpty {
            get {
                return ResourceManager.GetString("SequenceNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored procedure name for condition {0} must be specified.
        /// </summary>
        internal static string StoredProcedureNameEmpty {
            get {
                return ResourceManager.GetString("StoredProcedureNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name for condition {0} must be specified.
        /// </summary>
        internal static string TableNameEmpty {
            get {
                return ResourceManager.GetString("TableNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger name for condition{0} must be specified.
        /// </summary>
        internal static string TriggerNameEmpty {
            get {
                return ResourceManager.GetString("TriggerNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name must be specified as a parameter for condition {0}.
        /// </summary>
        internal static string UserNotFoundUserNotSpecified {
            get {
                return ResourceManager.GetString("UserNotFoundUserNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View name for condition {0} must be specified.
        /// </summary>
        internal static string ViewNameEmpty {
            get {
                return ResourceManager.GetString("ViewNameEmpty", resourceCulture);
            }
        }
    }
}
