//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKeeperNet.Engine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateContextMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateContextMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbKeeperNet.Engine.Resources.UpdateContextMessages", typeof(UpdateContextMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging service can&apos;t be initialized.
        /// </summary>
        internal static string CanNotInitializeLoggingService {
            get {
                return ResourceManager.GetString("CanNotInitializeLoggingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database service &apos;{0}&apos; already registered.
        /// </summary>
        internal static string DatabaseServiceAlreadyRegistered {
            get {
                return ResourceManager.GetString("DatabaseServiceAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized database service for connection string &apos;{0}&apos;.
        /// </summary>
        internal static string DatabaseServiceInitialized {
            get {
                return ResourceManager.GetString("DatabaseServiceInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For connection string &apos;{0}&apos; found database service &apos;{1}&apos;.
        /// </summary>
        internal static string DatabaseServiceMappingFound {
            get {
                return ResourceManager.GetString("DatabaseServiceMappingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database service mapping for connection string &apos;{0}&apos; not found.
        /// </summary>
        internal static string DatabaseServiceMappingNotFound {
            get {
                return ResourceManager.GetString("DatabaseServiceMappingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database service property &apos;Name&apos; must be non-empty.
        /// </summary>
        internal static string DatabaseServiceNameNull {
            get {
                return ResourceManager.GetString("DatabaseServiceNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database service is not initialized.
        /// </summary>
        internal static string DatabaseServiceNotInitialized {
            get {
                return ResourceManager.GetString("DatabaseServiceNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database service &apos;{0}&apos; not registered.
        /// </summary>
        internal static string DatabaseServiceNotRegistered {
            get {
                return ResourceManager.GetString("DatabaseServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging service &apos;{0}&apos; already registered.
        /// </summary>
        internal static string LoggingServiceAlreadyRegistered {
            get {
                return ResourceManager.GetString("LoggingServiceAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging service property &apos;Name&apos; must be non-empty.
        /// </summary>
        internal static string LoggingServiceNameNull {
            get {
                return ResourceManager.GetString("LoggingServiceNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging service &apos;{0}&apos; is not registered.
        /// </summary>
        internal static string LoggingServiceNotRegistered {
            get {
                return ResourceManager.GetString("LoggingServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition &apos;{0}&apos; already registered.
        /// </summary>
        internal static string PreconditionAlreadyRegistered {
            get {
                return ResourceManager.GetString("PreconditionAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition property &apos;Name&apos; must be non-empty.
        /// </summary>
        internal static string PreconditionNameNull {
            get {
                return ResourceManager.GetString("PreconditionNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching database service for connection string &apos;{0}&apos;.
        /// </summary>
        internal static string SearchingDatabaseService {
            get {
                return ResourceManager.GetString("SearchingDatabaseService", resourceCulture);
            }
        }
    }
}
