//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKeeperNet.Engine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdaterMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdaterMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbKeeperNet.Engine.Resources.UpdaterMessages", typeof(UpdaterMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A common exception caught during update, will rethrow: {0}.
        /// </summary>
        internal static string CaughtCommonException {
            get {
                return ResourceManager.GetString("CaughtCommonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception caught during update: {0}.
        /// </summary>
        internal static string CaughtException {
            get {
                return ResourceManager.GetString("CaughtException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking precondition: {0} - not supported [result={1}].
        /// </summary>
        internal static string CheckingPreconditionNotSupported {
            get {
                return ResourceManager.GetString("CheckingPreconditionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking precondition: {0} [result={1}].
        /// </summary>
        internal static string CheckingPreconditionResult {
            get {
                return ResourceManager.GetString("CheckingPreconditionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking precondition: {0} [{1}] {{{2}}}.
        /// </summary>
        internal static string CheckingStepPrecondition {
            get {
                return ResourceManager.GetString("CheckingStepPrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking step &apos;{0}&apos; preconditions.
        /// </summary>
        internal static string CheckingStepPreconditions {
            get {
                return ResourceManager.GetString("CheckingStepPreconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions result to: {0}.
        /// </summary>
        internal static string CheckingStepPreconditionsResult {
            get {
                return ResourceManager.GetString("CheckingStepPreconditionsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error detected during updates execution.
        /// </summary>
        internal static string CommonExceptionMessage {
            get {
                return ResourceManager.GetString("CommonExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to check database setup.
        /// </summary>
        internal static string DatabaseSetupCheck {
            get {
                return ResourceManager.GetString("DatabaseSetupCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database setup script finished.
        /// </summary>
        internal static string DatabaseSetupFinished {
            get {
                return ResourceManager.GetString("DatabaseSetupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No database setup necessary.
        /// </summary>
        internal static string DatabaseSetupNotNecessary {
            get {
                return ResourceManager.GetString("DatabaseSetupNotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database setup script will be executed.
        /// </summary>
        internal static string DatabaseSetupToBeExecuted {
            get {
                return ResourceManager.GetString("DatabaseSetupToBeExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing updates for assembly: {0}.
        /// </summary>
        internal static string ExecutingUpdatesForAssembly {
            get {
                return ResourceManager.GetString("ExecutingUpdatesForAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates for assembly executed successfully: {0}.
        /// </summary>
        internal static string ExecutingUpdatesForAssemblyFinished {
            get {
                return ResourceManager.GetString("ExecutingUpdatesForAssemblyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update file &apos;{0}&apos; not found on disk.
        /// </summary>
        internal static string FileUpdateNotFound {
            get {
                return ResourceManager.GetString("FileUpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully executed configured disk file update &apos;{0}&apos;.
        /// </summary>
        internal static string FinishedConfiguredFileUpdate {
            get {
                return ResourceManager.GetString("FinishedConfiguredFileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully executed configured update &apos;{0}&apos; in assembly &apos;{1}&apos;.
        /// </summary>
        internal static string FinishedConfiguredUpdate {
            get {
                return ResourceManager.GetString("FinishedConfiguredUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished step: {0} [{1}].
        /// </summary>
        internal static string FinishedUpdateStep {
            get {
                return ResourceManager.GetString("FinishedUpdateStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished version with success: {0} [{1}].
        /// </summary>
        internal static string FinishedVersion {
            get {
                return ResourceManager.GetString("FinishedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest resource &apos;{0}&apos; in assembly &apos;{1}&apos; not found.
        /// </summary>
        internal static string ManifestResourceNotFound {
            get {
                return ResourceManager.GetString("ManifestResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to execute configured update &apos;{0}&apos; from disk file.
        /// </summary>
        internal static string StartingConfiguredFileUpdate {
            get {
                return ResourceManager.GetString("StartingConfiguredFileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to execute configured update &apos;{0}&apos; in assembly &apos;{1}&apos;.
        /// </summary>
        internal static string StartingConfiguredUpdate {
            get {
                return ResourceManager.GetString("StartingConfiguredUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running step: {0} [{1}].
        /// </summary>
        internal static string StartingUpdateStep {
            get {
                return ResourceManager.GetString("StartingUpdateStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running version: {0} [{1}].
        /// </summary>
        internal static string StartingVersion {
            get {
                return ResourceManager.GetString("StartingVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception caught during update - executing transaction rollback.
        /// </summary>
        internal static string StepExceptionRollback {
            get {
                return ResourceManager.GetString("StepExceptionRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step executed information saved to database: {0} [{1}].
        /// </summary>
        internal static string StepMarkedAsExecuted {
            get {
                return ResourceManager.GetString("StepMarkedAsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping step: {0} [{1}].
        /// </summary>
        internal static string StepSkipped {
            get {
                return ResourceManager.GetString("StepSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported update step type.
        /// </summary>
        internal static string UnsupportedUpdateStepType {
            get {
                return ResourceManager.GetString("UnsupportedUpdateStepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preconditions declared - using context defaults.
        /// </summary>
        internal static string UsingDefaultPreconditions {
            get {
                return ResourceManager.GetString("UsingDefaultPreconditions", resourceCulture);
            }
        }
    }
}
