//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbKeeperNet.Engine.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdateStepVisitorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateStepVisitorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbKeeperNet.Engine.Resources.UpdateStepVisitorMessages", typeof(UpdateStepVisitorMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added role {0}.
        /// </summary>
        internal static string AddedRole {
            get {
                return ResourceManager.GetString("AddedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added user {0}.
        /// </summary>
        internal static string AddedUser {
            get {
                return ResourceManager.GetString("AddedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding role {0}.
        /// </summary>
        internal static string AddingRole {
            get {
                return ResourceManager.GetString("AddingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding user {0}.
        /// </summary>
        internal static string AddingUser {
            get {
                return ResourceManager.GetString("AddingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding user {0} to roles {1}.
        /// </summary>
        internal static string AddingUserToRoles {
            get {
                return ResourceManager.GetString("AddingUserToRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No relevant SQL statement found for driver: {0}.
        /// </summary>
        internal static string AlternativeSqlStatementNotFound {
            get {
                return ResourceManager.GetString("AlternativeSqlStatementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom step type &apos;{0}&apos; not found.
        /// </summary>
        internal static string CustomStepTypeNotFound {
            get {
                return ResourceManager.GetString("CustomStepTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted role {0}.
        /// </summary>
        internal static string DeletedRole {
            get {
                return ResourceManager.GetString("DeletedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted user {0}.
        /// </summary>
        internal static string DeletedUser {
            get {
                return ResourceManager.GetString("DeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting role {0}.
        /// </summary>
        internal static string DeletingRole {
            get {
                return ResourceManager.GetString("DeletingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user {0}.
        /// </summary>
        internal static string DeletingUser {
            get {
                return ResourceManager.GetString("DeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running part {0} of the command.
        /// </summary>
        internal static string ExecutingCommandPart {
            get {
                return ResourceManager.GetString("ExecutingCommandPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished part {0} of the command.
        /// </summary>
        internal static string FinishedCommandPart {
            get {
                return ResourceManager.GetString("FinishedCommandPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going to use adapter {0}.
        /// </summary>
        internal static string GoingToUseAdapter {
            get {
                return ResourceManager.GetString("GoingToUseAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} added to requested roles.
        /// </summary>
        internal static string UserAddedToRoles {
            get {
                return ResourceManager.GetString("UserAddedToRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not deleted.
        /// </summary>
        internal static string UserNotDeleted {
            get {
                return ResourceManager.GetString("UserNotDeleted", resourceCulture);
            }
        }
    }
}
